---
version: "3"

services:
  app:
    build: .
    depends_on:
      - redis
    ports:
      - 8080:8080
    environment:
      SPRING_REDIS_HOST: redis

  redis:
    image: redis:latest
    deploy:
      replicas: 1
    ports:
      - 6379:6379

